### ISSUE TITLE
Instructor Feedback

### ISSUE THREAD

**Issue by droxey** [AnniePawl/anna-backend#2]
@AnniePawl Great project! It's just missing a few of the requirements. In order to pass, could you address these points by EOD?

- Missing Bootstrap 4 in `main.handlebars`.
- Missing deployed Heroku link. You can add it to your `README`.

Thanks so much! Once you fix these two issues, you'll be good to go!
-d

**Comment by droxey** [comment]
Additionally, you'll need 100% test coverage of all routes.

**Comment by AnniePawl** [comment]
Thanks, Dani!
I'm on it. I'll give you a heads up once these elements are completed.
Anna

**Comment by droxey** [comment]
Great work! This is now passing! 👍
